// Code generated by "stringer -type=CardSuit"; DO NOT EDIT.

package deck

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Spades-0]
	_ = x[Diamonds-1]
	_ = x[Clubs-2]
	_ = x[Hearts-3]
	_ = x[JokerSuit-4]
}

const _CardSuit_name = "SpadesDiamondsClubsHeartsJokerSuit"

var _CardSuit_index = [...]uint8{0, 6, 14, 19, 25, 34}

func (i CardSuit) String() string {
	if i < 0 || i >= CardSuit(len(_CardSuit_index)-1) {
		return "CardSuit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CardSuit_name[_CardSuit_index[i]:_CardSuit_index[i+1]]
}
