// Code generated by "stringer -type=Suit -linecomment"; DO NOT EDIT.

package deck

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Spades-0]
	_ = x[Diamonds-1]
	_ = x[Clubs-2]
	_ = x[Hearts-3]
	_ = x[JokerSuit-4]
}

const _Suit_name = "♠♦♣♥JS"

var _Suit_index = [...]uint8{0, 3, 6, 9, 12, 14}

func (i Suit) String() string {
	if i < 0 || i >= Suit(len(_Suit_index)-1) {
		return "Suit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Suit_name[_Suit_index[i]:_Suit_index[i+1]]
}
